services:
  postgres:
    container_name: idp_postgres
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pythonapi
      - adminernet
    environment:
      POSTGRES_USER: 'idp_user'
      POSTGRES_PASSWORD: 'idp_pass'
      POSTGRES_DB: 'db_idp'

  pythonapi:
    container_name: idp_python_api
    build:
      context: db-microservice
    restart: always
    ports:
      - 6000:6000
    volumes:
      - ./db-microservice:/idp_db
    networks:
      - pythonapi
    depends_on:
      postgres:
        condition: service_healthy

  authapi:
    container_name: idp_auth_api
    build:
      context: auth-microservice
    restart: always
    ports:
      - 8888:6000
    volumes:
      - ./auth-microservice:/idp_auth
    networks:
      - pythonapi
      - adminernet
    depends_on:
      postgres:
        condition: service_healthy
      # keycloak:
      #   condition: service_healthy

  adminer:
    container_name: idp-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      postgres:
        condition: service_healthy
    networks:
      - adminernet

  keycloak:
    container_name: idp-keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    restart: always
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev
    volumes:
      - ./container-data/keycloak:/opt/keycloak/data/h2
    # healthcheck:
    #     test: ["CMD", "curl", "--head","fsS", "http://localhost:8090/health/ready"]
    #     interval: 5s
    #     timeout: 2s
    #     retries: 15
    networks:
      - pythonapi
      - adminernet

volumes:
  db-data:

networks:
  pythonapi:
  adminernet:
